# Generated by Django 4.2.1 on 2023-05-14 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0002_url_thoigian_url_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='ThoiGian',
            new_name='Time',
        ),
        migrations.DeleteModel(
            name='InformationUser',
        ),
    ]
