# Generated by Django 4.2.1 on 2023-05-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0003_rename_thoigian_url_time_delete_informationuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='User',
            new_name='user',
        ),
    ]
