# Generated by Django 4.2.1 on 2023-05-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0004_rename_user_url_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='user',
        ),
    ]
