# Generated by Django 4.2.1 on 2023-05-23 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField()),
                ('prediction', models.TextField()),
                ('conf_score', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
