# Generated by Django 3.2.19 on 2023-05-24 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URL',
            new_name='final_result',
        ),
        migrations.RenameField(
            model_name='final_result',
            old_name='prediction',
            new_name='prediction_final',
        ),
        migrations.CreateModel(
            name='static_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField()),
                ('prediction', models.TextField()),
                ('conf_score', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dynamic_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField()),
                ('brand_name', models.TextField()),
                ('prediction', models.TextField()),
                ('conf_score', models.TextField()),
                ('img_path', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
