# Generated by Django 3.2.19 on 2023-05-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_dynamic_result_virustotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamic_result',
            name='virustotal',
        ),
        migrations.AddField(
            model_name='final_result',
            name='vt_score',
            field=models.TextField(default='None'),
        ),
    ]
