# Generated by Django 3.2.19 on 2023-05-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230526_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamic_result',
            name='img_path',
        ),
        migrations.AddField(
            model_name='final_result',
            name='img_path',
            field=models.TextField(default=''),
        ),
    ]
