# Generated by Django 3.2.19 on 2023-05-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20230529_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_result',
            name='expiration_date',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='final_result',
            name='is_live',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='final_result',
            name='isp',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='final_result',
            name='registration_date',
            field=models.TextField(blank=True),
        ),
    ]
