# Generated by Django 3.2.19 on 2023-05-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_final_result_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_result',
            name='get_asn',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='final_result',
            name='get_os',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='final_result',
            name='scheme',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='final_result',
            name='subdomains',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='final_result',
            name='img_path',
            field=models.ImageField(upload_to='media/predicts/'),
        ),
    ]
