# Generated by Django 3.2.19 on 2023-06-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_final_result_loc_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_result',
            name='headers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='final_result',
            name='hostnames',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='final_result',
            name='status_code',
            field=models.TextField(blank=True),
        ),
    ]
