# Generated by Django 3.2.19 on 2023-06-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20230604_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_result',
            name='intended_life_span',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='final_result',
            name='last_updates_dates',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='final_result',
            name='life_remaining',
            field=models.TextField(blank=True),
        ),
    ]
