# Generated by Django 3.2.19 on 2023-06-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20230605_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_result',
            name='abnormal_subdomain',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='final_result',
            name='has_admin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='final_result',
            name='has_login',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='final_result',
            name='has_port_in_string',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='final_result',
            name='ip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='final_result',
            name='is_encoded',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='final_result',
            name='login_form',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='final_result',
            name='submit_email',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='final_result',
            name='suspecious_tld',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='final_result',
            name='tld',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='final_result',
            name='ttl',
            field=models.TextField(blank=True),
        ),
    ]
