# Generated by Django 3.2.19 on 2023-06-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_final_result_nameserverwhois'),
    ]

    operations = [
        migrations.RenameField(
            model_name='final_result',
            old_name='abnormal_subdomain',
            new_name='get_all_urls_from_wayback',
        ),
        migrations.RemoveField(
            model_name='final_result',
            name='is_encoded',
        ),
    ]
