# Generated by Django 3.2.19 on 2023-06-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_final_result_get_all_urls_from_wayback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final_result',
            name='get_os',
        ),
        migrations.RemoveField(
            model_name='final_result',
            name='login_form',
        ),
        migrations.RemoveField(
            model_name='final_result',
            name='submit_email',
        ),
    ]
