# Generated by Django 3.2.19 on 2023-06-28 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_final_result_htmlinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final_result',
            name='get_all_urls_from_wayback',
        ),
        migrations.RemoveField(
            model_name='final_result',
            name='has_admin',
        ),
        migrations.RemoveField(
            model_name='final_result',
            name='has_login',
        ),
    ]
